// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGFwxtUfhnEkuNJEhptEyo8p13Pb5uKn0',
    appId: '1:106792957965:web:c4b959875025c0bc7ebd44',
    messagingSenderId: '106792957965',
    projectId: 'totalhealthy-fd278',
    authDomain: 'totalhealthy-fd278.firebaseapp.com',
    storageBucket: 'totalhealthy-fd278.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3_huye73q1ye4vCRHuFNn0KqStnOWAf8',
    appId: '1:106792957965:android:8baa342400ba84807ebd44',
    messagingSenderId: '106792957965',
    projectId: 'totalhealthy-fd278',
    storageBucket: 'totalhealthy-fd278.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPKllTcjwWv-Ox73xlRnFiwJqCCJwlHKI',
    appId: '1:106792957965:ios:b45a85f4642264e87ebd44',
    messagingSenderId: '106792957965',
    projectId: 'totalhealthy-fd278',
    storageBucket: 'totalhealthy-fd278.firebasestorage.app',
    iosBundleId: 'com.example.totalhealthy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPKllTcjwWv-Ox73xlRnFiwJqCCJwlHKI',
    appId: '1:106792957965:ios:b45a85f4642264e87ebd44',
    messagingSenderId: '106792957965',
    projectId: 'totalhealthy-fd278',
    storageBucket: 'totalhealthy-fd278.firebasestorage.app',
    iosBundleId: 'com.example.totalhealthy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGFwxtUfhnEkuNJEhptEyo8p13Pb5uKn0',
    appId: '1:106792957965:web:0bd48bd7ffb8993c7ebd44',
    messagingSenderId: '106792957965',
    projectId: 'totalhealthy-fd278',
    authDomain: 'totalhealthy-fd278.firebaseapp.com',
    storageBucket: 'totalhealthy-fd278.firebasestorage.app',
  );
}
