part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const home = _Paths.home;
  static const swipeScreen = _Paths.swipeScreen;
  static const welcomeScreen = _Paths.welcomeScreen;
  static const registration = _Paths.registration;
  static const login = _Paths.login;
  static const nutritionGoal = _Paths.nutritionGoal;
  static const notification = _Paths.notification;
  static const generateAi = _Paths.generateAi;
  static const mealHistory = _Paths.mealHistory;
  static const mealsDetails = _Paths.mealsDetails;
  static const mealTiming = _Paths.mealTiming;
  static const mealCategories = _Paths.mealCategories;
  static const mealCategoriesManagement = _Paths.mealCategoriesManagement;
  static const groupCategories = _Paths.groupCategories;
  static const loginView = _Paths.mealTiming;
  static const forgetPassword = _Paths.forgetPassword;
  static const userDiet = _Paths.userDiet;
  static const trainerDashboard = _Paths.trainerDashboard;
  static const clientDashboard = _Paths.clientDashboard;
  static const createMeal = _Paths.createMeal;
  static const signup = _Paths.signup;
  static const group = _Paths.group;
  static const createGroup = _Paths.createGroup;
  static const groupDetails = _Paths.groupDetails;
  static const memberManagement = _Paths.memberManagement;
  static const onboarding = _Paths.onboarding;
  static const setting = _Paths.setting;
  static const generalSettings = _Paths.generalSettings;
  static const profileSettings = _Paths.profileSettings;
  static const notificationSettings = _Paths.notificationSettings;
  static const accountPasswordSettings = _Paths.accountPasswordSettings;
  static const profileMain = _Paths.profileMain;
  static const switchRole = _Paths.switchRole;
  static const clientList = _Paths.clientList;
  static const privacyPolicy = _Paths.privacyPolicy;
  static const planner = _Paths.planner;
  static const groupMealCalendar = _Paths.groupMealCalendar;
  static const weeklyMealPlanner = _Paths.weeklyMealPlanner;
}

abstract class _Paths {
  _Paths._();
  static const home = '/home';
  static const onboarding = '/onboarding';
  static const swipeScreen = '/swipescreen';
  static const welcomeScreen = '/welcomescreen';
  static const registration = '/registration';
  static const login = '/login';
  static const nutritionGoal = '/nutrition-goal';
  static const notification = '/notification';
  static const generateAi = '/generate-ai';
  static const mealHistory = '/meal-history';
  static const mealsDetails = '/meals-details';
  static const mealTiming = '/meal-timing';
  static const mealCategories = '/meal-categories';
  static const mealCategoriesManagement = '/meal-categories-management';
  static const groupCategories = '/group-categories';
  static const userDiet = '/userdiet';
  static const trainerDashboard = '/trainerdashboard';
  static const clientDashboard = '/clientdashboard';
  static const createMeal = '/createmeal';
  static const signup = '/signup';
  static const forgetPassword = '/forgot-password';
  static const group = '/group';
  static const createGroup = '/create-group';
  static const groupDetails = '/group-details';
  static const memberManagement = '/member-management';
  static const setting = '/setting';
  static const generalSettings = '/general-settings';
  static const profileSettings = '/profile-settings';
  static const notificationSettings = '/notification-settings';
  static const accountPasswordSettings = '/account-password-settings';
  static const profileMain = '/profile-main';
  static const switchRole = '/switch-role';
  static const clientList = '/client-list';
  static const privacyPolicy = '/privacy-policy';
  static const planner = '/planner';
  static const groupMealCalendar = '/group-meal-calendar';
  static const weeklyMealPlanner = '/weekly-meal-planner';
}
